services:
  comfyui-worker:
    image: ghcr.io/halkony/worker-comfyui:latest-flux1-kontext-dev-fp8
    build:
      context: .
      target: final
      args:
        MODEL_TYPE: flux1-kontext-dev-fp8
        HUGGINGFACE_ACCESS_TOKEN: ${HUGGINGFACE_ACCESS_TOKEN:-}
    pull_policy: never
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/runpod-volume:/runpod-volume
